lecteurcarte.o: lecteurcarte.c lecteurcarte.h \
 /shared/TCii/include/lcarte.h
borne.o: borne.c /shared/TCii/include/memoire_borne.h \
 /shared/TCii/include/donnees_borne.h \
 /shared/TCii/include/donnees_borne.h lecteurcarte.h \
 /shared/TCii/include/lcarte.h
