lecteurcarte.o: lecteurcarte.cpp lecteurcarte.h voyant.h global.h \
 bouton.h Timer.h baseclient.h generateur_save.h
borne.o: borne.cpp voyant.h global.h lecteurcarte.h bouton.h Timer.h \
 baseclient.h generateur_save.h reprise.h prise.h
baseclient.o: baseclient.cpp baseclient.h global.h
bouton.o: bouton.cpp bouton.h
generateur_save.o: generateur_save.cpp generateur_save.h global.h
prise.o: prise.cpp prise.h global.h
reprise.o: reprise.cpp reprise.h voyant.h global.h prise.h baseclient.h \
 generateur_save.h
Timer.o: Timer.cpp Timer.h global.h
voyant.o: voyant.cpp voyant.h global.h
